Added CowDeathTable react component, storybook, fixures and tests
ucsb-cs156-f22/f22-7pm-happycows pull request #53
Opened 2022-11-29 05:27 UTC by minhbui27

In this commit, I added the CowDeathTable react component (frontend) only with no endpoints (those are for other issues), a storybook component along with fixtures, and tests.

Closes #50

2022-11-29 22:19 UTC, RAILGUN1124 approved these changes
I approve

2022-11-30 01:21 UTC, ethwu commented on frontend/src/fixtures/CowDeathFixtures.js
> +						"avgHealth": 20
Probably should replace these tabs with 4 spaces

2022-11-30 01:21 UTC, blakerandle requested changes
I am confused by why the header for one of the columns in CowDeathTable.js is 'ZonedDateTime' rather than something like 'Created At.' I understand it is technically in the spec but it seems like a typo and would be confusing to a user.

2022-11-30 01:37 UTC, blakerandle approved these changes
lgtm

2022-11-30 01:41 UTC, ethwu approved these changes

2022-12-01 17:18 UTC, pconrad approved these changes
LGTM

2022-12-01 17:18 UTC, merged