Implemented CowDeathController
ucsb-cs156-f22/f22-7pm-happycows pull request #66
Opened 2022-11-30 23:14 UTC by KaieChen

In this pull request, the CowDeathController has been implemented with three routes:

1. POST as admin
2. GET by commonId: Returns a list of CowDeath entities
3. GET by commonId and userId: Returns a CowDeath entity

These can be tested by the following:

2022-11-30 23:48 UTC, blakerandle requested changes, later dismissed
There are a few spots that have commented out lines of code which should be removed before merging to main.

2022-11-30 23:48 UTC, blakerandle commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +//import java.time.LocalDateTime;
I think it would be good practice to remove these commented out lines of code

2022-11-30 23:48 UTC, blakerandle commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +  //List<CowDeath> expectedCowDeaths = new ArrayList<CowDeath>();
^

2022-11-30 23:48 UTC, blakerandle commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +  //expectedCowDeaths.add(cowDeathSample);
^

2022-11-30 23:56 UTC, blakerandle approved these changes, later dismissed
lgtm

2022-11-30 23:59 UTC, RAILGUN1124 approved these changes, later dismissed
lgtm

2022-12-01 03:06 UTC, bzamora020 submitted a review, later dismissed
Heroku throws a 400 error on the post requests

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/33767941/204956422-3321804c-cae8-4abd-b591-0e2545ecbaa0.png">

2022-12-01 03:43 UTC, bzamora020 submitted a review, later dismissed
Tested and works as expected in Heroku QA as well as locally

2022-12-01 04:09 UTC, pconrad submitted a review, later dismissed
Some changes are needed... see below

2022-12-01 04:09 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +            @ApiParam("createdAt") @RequestParam("createdAt") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) ZonedDateTime createdAt,
Created At should not be a parameter.  Instead, it should be automatically assigned the same way we assign the createdAt for jobs.   You can just remove it here.

2022-12-01 04:09 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +
Before storing the userId and the commonsId, check that they are valid.

I'll send you some sample code.

2022-12-01 04:09 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +    .createdAt(someTime)
remove the createdAt here...

2022-12-01 18:42 UTC, RAILGUN1124 approved these changes, later dismissed
lgtm

2022-12-07 05:17 UTC, pconrad requested changes, later dismissed
Please follow professional standards when submitting code in PRs, now and more importantly, when you represent UCSB in the future.

I will be very embarassed if you go away from this course and are still submitting code like this in PRs.

2022-12-07 05:17 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +        //}
Please remove this commented out code.   We actually don't want this feature, and leaving this comment in suggests that perhaps we do. 

In fact, we WILL have the possiblity of multiple cow deaths happening over time for the same commonsId/userId, just on different days.

This is an example of WHY we don't want commented out code in PRs that get merged into main. It creates the potential for confusion among future developers.

Please remove this

2022-12-07 05:17 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +}
The indentation here is not standard.   Please follow the indentation conventions of the rest of the code base.

This is easy to do if you use VSCode and install the recommended Microsoft Java Extensions.

You just use the "format code" key stroke and it's all done for you.  It is  unprofessional to submit code for review that doesn't have consistent indentation.

2022-12-07 08:26 UTC, KaieChen commented on src/main/java/edu/ucsb/cs156/happiercows/repositories/CowDeathRepository.java
> +	Optional<CowDeath> getCowsKilledByCommonsIdAndUserId(Long commons_id, Long user_id );
I don't know why there is an extra tab being added. I deleted the tab and pushed again but it is still here.

2022-12-08 01:12 UTC, FinalGale approved these changes, later dismissed
LGTM

2022-12-08 01:30 UTC, blakerandle requested changes
A few minor styling changes to consider. Overall looking good though

2022-12-08 01:30 UTC, blakerandle commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +      @ApiParam("commonsId") @RequestParam Long commonsId, @ApiParam("userId") @RequestParam Long userId) throws JsonProcessingException {
Should the arguments be separated on different lines like postCowDeath()? This is a fairly long line and you have already started one newline.

2022-12-08 01:30 UTC, blakerandle commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +           .with(csrf())).andExpect(status().isNotFound());
Double tab I think.

2022-12-08 01:32 UTC, blakerandle commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +      @ApiParam("commonsId") @RequestParam Long commonsId, @ApiParam("userId") @RequestParam Long userId) throws JsonProcessingException {
To be clear I'm not sure if this is necessary. Just something to consider

2022-12-08 01:34 UTC, KaieChen commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
> +      @ApiParam("commonsId") @RequestParam Long commonsId, @ApiParam("userId") @RequestParam Long userId) throws JsonProcessingException {
Yes, I will make it consistent with the the rest of the code, so I will make it on separate lines like the code base i.e. commonsController.

2022-12-08 01:35 UTC, KaieChen commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
> +           .with(csrf())).andExpect(status().isNotFound());
That is not good, I will fix it

2022-12-08 01:53 UTC, blakerandle submitted a review, later dismissed
lgtm

2022-12-08 02:05 UTC, FinalGale requested changes
For consistent code styling, delete extra newline in test function on line 100 of src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
![image](https://user-images.githubusercontent.com/46613691/206338780-76e1fe44-0f8e-4f8b-b1b4-a89dbee5b3f2.png)

2022-12-08 02:14 UTC, blakerandle approved these changes
lgtm

2022-12-08 02:14 UTC, FinalGale approved these changes
LGTM

2023-07-03 17:21 UTC, closed without merging